language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - npm install


  
script:

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t d94888/travis-ci:latest .
  - docker push d94888/travis-ci:latest

